# Generated by Django 2.1.1 on 2018-09-01 17:50

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('summary', models.CharField(blank=True, max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('text', markdownx.models.MarkdownxField()),
                ('is_published', models.BooleanField(default=False)),
                ('date_published', models.DateTimeField(blank=True)),
            ],
            options={
                'ordering': ['-is_published', '-date_published', '-date_created'],
            },
        ),
    ]
